name: Replace old links with archived links
on:
  schedule:
    - cron: "14 4 * * *"
  workflow_dispatch:
  push:
    branches: [linkrot.yml]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix links
        uses: tmcw/notfoundbot@4e949b57be585dcd81a39c23c6f6eacb51f1df69
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
